authapp/urls.py
from django.urls import path

from authapp.views import login, register, profile, logout

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
]

basketapp/urls.py
from django.urls import path

from basketapp.views import basket_add, basket_remove, basket_edit

app_name = 'basketapp'

urlpatterns = [
    path('add/<int:product_id>/', basket_add, name='basket_add'),
    path('remove/<int:id>/', basket_remove, name='basket_remove'),
    path('edit/<int:id>/<int:quantity>/', basket_edit, name='basket_edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mainapp.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name = 'index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('users/', include('authapp.urls', namespace='users')),
    path('baskets/', include('basketapp.urls', namespace='baskets')),
    path('admin-staff/', include('adminapp.urls', namespace='admin_staff')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

basketapp/models.py
from django.db import models

from authapp.models import User
from mainapp.models import Product


class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Корзина для {self.user.username} | Продукт {self.product.name}'

    def sum(self):
        return self.quantity * self.product.price

    def total_quantity(self):
        baskets = Basket.objects.filter(user=self.user)
        return sum(basket.quantity for basket in baskets)

    def total_sum(self):
        baskets = Basket.objects.filter(user=self.user)
        return sum(basket.sum() for basket in baskets)

basketapp/views.py
from django.shortcuts import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.http import JsonResponse

from mainapp.models import Product
from basketapp.models import Basket


@login_required
def basket_add(request, product_id=None):
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_remove(request, id):
    Basket.objects.get(id=id).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def basket_edit(request, id, quantity):
    if request.is_ajax():
        basket = Basket.objects.get(id=id)
        if quantity > 0:
            basket.quantity = quantity
            basket.save()
        else:
            basket.delete()
        baskets = Basket.objects.filter(user=request.user)
        context = {'baskets': baskets}
        result = render_to_string('basketapp/basket.html', context)
        return JsonResponse({'result': result})

basketapp/templates/basketapp/basket.html
<div class="basket_list">
    {% if baskets %}
        <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
            Корзина <span class="badge badge-secondary badge-pill">{{ baskets.0.total_quantity }}</span>
        </h4>
        {% for basket in baskets %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ basket.product.name }}</h5>
                    <p class="card-text">{{ basket.product.description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item bg-light">
                        <div class="row text-center">
                            <div class="col-lg-4">
                                <input name="{{ basket.id }}" type="number" class="form-control"
                                       value="{{ basket.quantity }}" min="0">
                            </div>
                            <div class="col-lg-4">{{ basket.sum }} руб.</div>
                            <div class="col-lg-4">
                                <a href="{% url 'baskets:basket_remove' basket.id %}">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        {% endfor %}
        <div class="card mb-3">
            <div class="card-footer">
                <p class="float-left">Итого</p>
                <h4 class="float-right">{{ baskets.0.total_sum }} руб.</h4>
            </div>
        </div>
        <button type="button" class="btn btn-success btn-lg float-right">Оформить</button>
    {% else %}
        <h4 class="mt-3 mb-3 text-center">
            Корзина пуста
        </h4>
    {% endif %}
</div>