adminapp/urls.py
from django.urls import path

from adminapp.views import index, UserListView, UserCreateView, UserUpdateView, UserDeleteView

app_name = 'adminapp'

urlpatterns = [
    path('', index, name='index'),
    path('admin-users-read/', UserListView.as_view(), name='admin_users_read'),
    path('admin-users-create/', UserCreateView.as_view(), name='admin_users_create'),
    path('admin-users-update/<int:pk>/', UserUpdateView.as_view(), name='admin_users_update'),
    path('admin-users-remove/<int:pk>/', UserDeleteView.as_view(), name='admin_users_remove'),
]

authapp/urls.py
from django.urls import path

from authapp.views import login, register, profile, logout

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mainapp.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name = 'index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('users/', include('authapp.urls', namespace='users')),
    path('baskets/', include('basketapp.urls', namespace='baskets')),
    path('admin-staff/', include('adminapp.urls', namespace='admin_staff')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

from mainapp.views import products

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='index'),
    path('<int:category_id>/', products, name='product'),
    path('page/<int:page>/', products, name='page'),
]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms

from authapp.forms import UserRegisterForm, UserProfileForm
from authapp.models import User


class UserAdminRegisterForm(UserRegisterForm):
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'custom-file-input'}), required=False)

    class Meta:
        model = User
        fields = ('username', 'email', 'image', 'first_name', 'last_name', 'password1', 'password2')


class UserAdminProfileForm(UserProfileForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control py-4'}))

adminapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import user_passes_test
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator

from authapp.models import User
from adminapp.forms import UserAdminRegisterForm, UserAdminProfileForm


@user_passes_test(lambda u: u.is_superuser)
def index(request):
    return render(request, 'adminapp/admin.html')


# CRUD - Create Read Update Delete
class UserListView(ListView):
    model = User
    template_name = 'adminapp/admin-users-read.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(UserListView, self).dispatch(request, *args, **kwargs)


class UserCreateView(CreateView):
    model = User
    template_name = 'adminapp/admin-users-create.html'
    form_class = UserAdminRegisterForm
    success_url = reverse_lazy('admin_staff:admin_users_read')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(UserCreateView, self).dispatch(request, *args, **kwargs)


class UserUpdateView(UpdateView):
    model = User
    template_name = 'adminapp/admin-users-update-delete.html'
    success_url = reverse_lazy('admin_staff:admin_users_read')
    form_class = UserAdminProfileForm

    def get_context_data(self, **kwargs):
        context = super(UserUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'GeekShop Admin - Редактирование пользователя'
        return context


class UserDeleteView(DeleteView):
    model = User
    template_name = 'adminapp/admin-users-update-delete.html'
    success_url = reverse_lazy('admin_staff:admin_users_read')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(success_url)

adminapp/templates/adminapp/admin-users-create.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <h1 class="mt-4">Создание пользователя</h1>
    <form action="{% url 'admin_staff:admin_users_create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-lg-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                    {{ form.first_name }}
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                    {{ form.last_name }}
                </div>
            </div>
        </div>
        <div class="form-row mb-2">
            <div class="col-lg-12">
                <div class="custom-file">
                    {{ form.avatar }}
                    <label class="custom-file-label" for="{{ form.avatar.id_for_label }}">Выберите изображение</label>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="col-lg-6">
                <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                {{ form.username }}
            </div>
            <div class="col-lg-6">
                <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                    почты</label>
                {{ form.email }}
            </div>
        </div>
        <div class="form-row">
            <div class="col-lg-6">
                <label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                {{ form.password1 }}
            </div>
            <div class="col-lg-6">
                <label class="small mb-1" for="{{ form.password2.id_for_label }}">Повторите пароль</label>
                {{ form.password2 }}
            </div>
        </div>
        <div class="form-row">
            <div class="col-lg-12" style="margin-top: 33px;">
                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
            </div>
        </div>
    </form>
{% endblock %}

adminapp/templates/adminapp/admin-users-read.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <h1 class="mt-4">Пользователи</h1>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table mr-1"></i>
            Пользователи
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Имя пользователя</th>
                        <th>Имя</th>
                        <th>Фамилия</th>
                        <th>Адрес эл. почты</th>
                        <th>Персонал сайта</th>
                        <th>Активный</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>Имя пользователя</th>
                        <th>Имя</th>
                        <th>Фамилия</th>
                        <th>Адрес эл. почты</th>
                        <th>Персонал сайта</th>
                        <th>Активный</th>
                    </tr>
                    </tfoot>
                    <tbody>
                    {% for user in object_list %}
                        <tr>
                            <td>
                                <a href="{% url 'admin_staff:admin_users_update' user.id %}" style="color: dodgerblue">
                                    {{ user.username }}
                                </a>
                            </td>
                            <td>{{ user.first_name }}</td>
                            <td>{{ user.last_name }}</td>
                            <td>{{ user.email }}</td>
                            <td class="text-center">
                                {% if user.is_staff %}
                                    <i class="fas fa-check-circle"></i>
                                {% else %}
                                    <i class="fas fa-times-circle"></i>
                                {% endif %}
                            </td>
                            <td class="text-center">
                                {% if user.is_active %}
                                    <i class="fas fa-check-circle"></i>
                                {% else %}
                                    <i class="fas fa-times-circle"></i>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer">
            <a href="{% url 'admin_staff:admin_users_create' %}">
                <button class="btn btn-success">Создать пользователя</button>
            </a>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/admin-users-update-delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <h1 class="mt-4">Редактирование пользователя | {{ user.username }}</h1>
    <div class="card-body">
        <form action="{% url 'admin_staff:admin_users_update' user.id %}" method="post"
              enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                        {{ form.first_name }}
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                        {{ form.last_name }}
                    </div>
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="col-lg-12">
                    <div class="custom-file">
                        {{ form.avatar }}
                        <label class="custom-file-label" for="{{ form.avatar.id_for_label }}">Выберите
                            изображение</label>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-6">
                    <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                    {{ form.username }}
                </div>
                <div class="col-lg-6">
                    <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                        почты</label>
                    {{ form.email }}
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-12" style="margin-top: 33px;">
                    <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                </div>
            </div>
        </form>
        <div class="row">
            <div class="col-lg-12" style="margin-top: 33px;">
                <form action="{% url 'admin_staff:admin_users_remove' user.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Удалить" class="btn btn-danger btn-block">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/admin.html
{% extends 'adminapp/base.html' %}
{% block content %}
    <h1 class="mt-4">Административная панель</h1>
{% endblock %}

adminapp/templates/adminapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title }}</title>
    <link href="{% static 'auth-admin.css' %}" rel="stylesheet"/>
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet"
          crossorigin="anonymous"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'mainapp:index' %}">GeekShop</a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i>
    </button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Поиск..." aria-label="Search"
                   aria-describedby="basic-addon2"/>
            <div class="input-group-append">
                <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'authapp:logout' %}">Logout</a>
            </div>
        </li>
    </ul>
</nav>
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Приложения</div>
                    <a class="nav-link" href="{% url 'admin_staff:admin_users_read' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-users"></i>
                        </div>
                        Пользователи
                    </a>
                    <a class="nav-link" href="base.html">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-shopping-basket"></i>
                        </div>
                        Категории
                    </a>
                    <a class="nav-link" href="base.html">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-tshirt"></i>
                        </div>
                        Продукты
                    </a>
                </div>
            </div>
            <div class="sb-sidenav-footer"></div>
        </nav>
    </div>
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                {% block content %} {% endblock %}
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/auth-admin.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
<script src="{% static 'js/datatable.js' %}"></script>
</body>
</html>