authapp/urls.py
from django.urls import path

from authapp.views import login, register, profile, logout

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
]

basketapp/urls.py
from django.urls import path

from basketapp.views import basket_add, basket_remove, basket_edit

app_name = 'basketapp'

urlpatterns = [
    path('add/<int:product_id>/', basket_add, name='basket_add'),
    path('remove/<int:id>/', basket_remove, name='basket_remove'),
    path('edit/<int:id>/<int:quantity>/', basket_edit, name='basket_edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mainapp.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name = 'index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('users/', include('authapp.urls', namespace='users')),
    path('baskets/', include('basketapp.urls', namespace='baskets')),
    path('admin-staff/', include('adminapp.urls', namespace='admin_staff')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

from mainapp.views import products

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='index'),
    path('<int:category_id>/', products, name='product'),
    path('page/<int:page>/', products, name='page'),
]

mainapp/models.py
from django.db import models

class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = 'Product Categories'

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=256, unique=True)
    image = models.ImageField(upload_to='products_images', blank=True)
    description = models.CharField(max_length=64, unique=True, blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}|{self.category.name}'

mainapp/views.py
from django.shortcuts import render

from mainapp.models import Product, ProductCategory
from django.views.generic.list import ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def index(request):
    context = {'title': 'GeekShop'}
    return render(request, 'mainapp/index.html', context)

class ProductsListView(ListView):
    model = Product
    template_name = 'mainapp/products.html'

    def get_context_data(self, **kwargs):
        context = super(ProductsListView, self).get_context_data(**kwargs)
        context['title'] = 'GeekShop - Каталог'
        context['categories'] = ProductCategory.objects.all()
        context['products'] = Product.objects.all()
        return context
    def get(self, request, *args, **kwargs):
        pass
#def products(request, category_id=None, page=1):
#    context = {'title': 'GeekShop - Каталог', 'categories': ProductCategory.objects.all()}
#    products = Product.objects.filter(category_id=category_id) if category_id else Product.objects.all()
#    paginator = Paginator(products, per_page=2)
#    try:
#        products_paginator = paginator.page(page)
#    except PageNotAnInteger:
#        products_paginator = paginator.page(1)
#    except EmptyPage:
#        products_paginator = paginator.page(paginator.num_pages)
#    context.update({'products': products_paginator})
#    return render(request, 'mainapp/products.html', context)

mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    {% block title %} {% endblock %}
    {% block css %} {% endblock %}
</head>
<body>
    {% block content %} {% endblock %}
    {% block footer %} {% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/basket.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static 'js/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>
</html>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %}
	<title>{{ title|title }} {% now "Y" %}</title>
{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'style.css' %}">
<link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
{% endblock %}
{% block content %}
	<div class="container">
		<div class="slider">
			<div class="header clearfix">
				<a href="{% url 'index' %}" class="logo"></a>
				<ul class="menu">
					<li><a href="{% url 'index' %}" class="active">домой</a></li>
					<li><a href="{% url 'products:index' %}">продукты</a></li>
					<li><a href="contact.html">Контакты</a></li>
					{% if user.is_staff or user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin_staff:index' %}">
                                <i class="fas fa-users-cog"></i>
                            </a>
                        </li>
                    {% endif %}
					{% if user.is_authenticated %}
					<li><a href="{% url 'users:logout' %}">Выйти</a></li>
					<li><a href="{% url 'users:profile' %}">Личный кабинет</a></li>
					{% else %}
					<li><a href="{% url 'users:login' %}">Войти</a></li>
					{% endif %}
				</ul>
				<a href="#" class="search"></a>
			</div>
			<div class="text-slider">
				<h3 class="green">тенденции</h3>
				<h3 class="big"> удобные стулья</h3>
				<p>Новый уровень комфорта. Отличные характеристики.</p>
				<a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
			</div>
			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>
		</div>

		<div class="featured">
			<div class="featured-menu">
					<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
			</div>
			<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
			<div class="clearfix">
			</div>
			<div class="tab-content">
				<div class="block">
					<a href="#"><img src="{% static 'img/product-1.jpg '%}" alt="">
						<div class="text">
							<img src="{% static 'img/icon-hover.png' %}" alt="img">
							<h4>Отличный стул</h4>
							<p>Расположитесь комфортно. </p>
						</div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{% static 'img/product-2.jpg' %}" alt="">
						<div class="text">
							<img src="{% static 'img/icon-hover.png' %}" alt="">
							<h4>Стул повышенного качества</h4>
							<p>Не оторваться. </p>
						</div>
					</a>
				</div>
			</div>
		</div>

		<div class="clr"></div>

	</div>
{% endblock %}
{% block footer %}
	<div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %}
	<title>{{ title }}</title>
{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'style.css' %}">
<link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
{% endblock %}
{% block content %}
	<div class="container">
		<div class="hero-white">
			<div class="header clearfix">
				<a href="{% url 'index' %}" class="logo"></a>
				<ul class="menu">
					<li><a href="{% url 'index' %}">домой</a></li>
					<li><a href="{% url 'products:index' %}" class="active">продукты</a></li>
					<li><a href="contact.html">контакты</a></li>
					{% if user.is_authenticated %}
					<li><a href="{% url 'users:logout' %}">Выйти</a></li>
					<li><a href="{% url 'users:profile' %}">Личный кабинет</a></li>
					{% else %}
					<li><a href="{% url 'users:login' %}">Войти</a></li>
					{% endif %}
				</ul>
			</div>
		</div>

		<div class="details">
			<div class="links clearfix">

					<ul class="links-menu">
						{% for category in categories %}
							<li><a href="{% url 'mainapp:product' category.id %}"
								   class="active">{{category.name}}</a></li>
						{% endfor %}
					</ul>

			</div>

			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
						<img src="/media/products_images/slider1_0SF8fkn.jpg">
					</div>
					<div class="slider-control">
						<div class="block">
							<a href="#"><img src="{% static 'img/controll.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="{% static 'img/controll1.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="{% static 'img/controll2.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
					</div>
				</div>

				<div class="description">
					{% for product in products %}
						<h3 class="big-bold">{{ product.name }}</h3>
						<h3 class="red">{{ product.description }}</h3>
						<p class="price">{{ product.price }}<span> руб</span></p>
						<a href="{% url 'baskets:basket_add' product.id %}" class="red-button">
							заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
						</a>
						<div class="description-text">
							<p>Расположитесь комфортно.</p>
							<p>Отличное качество материалов позволит вам это.</p>
							<p>Различные цвета</p>
							<p>высочайший уровень эргономики и прочность.</p>
						</div>
					{% endfor %}
				</div>

			</div>

			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
				</div>
				<div class="related-products clearfix">
					<div class="block">
						<a href="#"><img src="{% static 'img/product-11.jpg' %}" alt="">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{% static 'img/product-21.jpg' %}" alt="">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{% static 'img/product-31.jpg' %}" alt="">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>

				</div>
			</div>
		</div>

		<div class="clr"></div>

	</div>
{% endblock %}
{% block footer %}
	<div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>
{% endblock %}